[package]
name = "weld"
version = "0.0.1-alpha.1"
authors = ["serayuzgur <serayuzgur@gmail.com>"]

[dependencies]
# Serde for JSON
serde="*"
serde_derive="*"
serde_json="*"

# Tokio for Server
bytes = "*"
futures = "*"
tokio-io = "*"
tokio-core = "*"
tokio-proto = "*"
tokio-service = "*"
tokio-minihttp = { git = "https://github.com/tokio-rs/tokio-minihttp" }
net2="*"
httparse="*"
# misc support for thread pools, random numbers, and json
futures-cpupool = "*"
rand = "*"

# Logger
slog= "*"
slog-term="*"

time="*"
lazy_static="*"