[package]
name = "weld"
version = "0.0.1-alpha"
authors = ["serayuzgur <serayuzgur@gmail.com>"]

[dependencies]
serde="*"
serde_derive="*"
serde_json="*"
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"