[package]
name = "weld"
version = "0.0.1-alpha.1"
license       = "MIT/Apache-2.0"
authors = ["serayuzgur <serayuzgur@gmail.com>"]
description   = """
A Mock Json Server Framework
"""
homepage      = "https://github.com/serayuzgur/weld"
repository    = "https://github.com/serayuzgur/weld"
readme        = "README.md"
keywords      = [ "json", "mock", "server" ]
exclude       = [
  ".gitignore",
  "tests/**/*",
]

[dependencies]
# Serde for JSON
serde="*"
serde_derive="*"
serde_json="*"

# Tokio for Server
bytes = "*"
futures = "*"
tokio-io = "*"
tokio-core = "*"
tokio-proto = "*"
tokio-service = "*"
tokio-minihttp = { git = "https://github.com/tokio-rs/tokio-minihttp" }
net2="*"
httparse="*"
# misc support for thread pools, random numbers, and json
futures-cpupool = "*"
rand = "*"

# Logger
slog= "2"
slog-term= { git = "https://github.com/slog-rs/term" }
slog-async= { git = "https://github.com/slog-rs/async" }

time="*"
lazy_static="*"